#!/bin/bash

# Auto-Build Environment Setup for Robust Error Handling
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Robust Error Handling & Recovery System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Backend WebSocket Server
echo "Starting Backend WebSocket Server..."
cd backend && python main.py &
BACKEND_PID=$!
wait_for_service 3004 "Backend WebSocket Server"

# Auto-Claude (if needed for agent testing)
echo "Starting Auto-Claude services..."
cd ../Auto-Claude/auto-claude && python run.py --help > /dev/null 2>&1 &
AUTO_CLAUDE_PID=$!

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend WebSocket: http://localhost:3004"
echo "  Health Check:     http://localhost:3004/health"
echo "  System Status:    http://localhost:3004/api/status"
echo ""
echo "PIDs for cleanup:"
echo "  Backend: $BACKEND_PID"
echo "  Auto-Claude: $AUTO_CLAUDE_PID"
echo ""
echo -e "${GREEN}Error handling development environment is ready!${NC}"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $AUTO_CLAUDE_PID"
echo ""

# Store PIDs for cleanup
echo $BACKEND_PID > .backend_pid
echo $AUTO_CLAUDE_PID > .auto_claude_pid

# Function to cleanup on exit
cleanup() {
    echo ""
    echo "Cleaning up..."
    if [ -f .backend_pid ]; then
        kill $(cat .backend_pid) 2>/dev/null || true
        rm .backend_pid
    fi
    if [ -f .auto_claude_pid ]; then
        kill $(cat .auto_claude_pid) 2>/dev/null || true
        rm .auto_claude_pid
    fi
    echo "Services stopped."
}

trap cleanup EXIT