#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Decision Capture & Tracking

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Decision Capture & Tracking System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Check prerequisites
echo "Checking prerequisites..."

# Check if spaCy model is downloaded
if ! python -c "import spacy; spacy.load('en_core_web_sm')" 2>/dev/null; then
    echo -e "${YELLOW}Downloading spaCy English model...${NC}"
    python -m spacy download en_core_web_sm
fi

# Check if PostgreSQL is running (if using PostgreSQL)
if command -v pg_isready >/dev/null 2>&1; then
    if pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
        echo -e "${GREEN}PostgreSQL is running${NC}"
    else
        echo -e "${YELLOW}PostgreSQL not running, starting with Docker...${NC}"
        docker run --name postgres-decisions -e POSTGRES_PASSWORD=password -e POSTGRES_DB=decisions -p 5432:5432 -d postgres 2>/dev/null || echo "PostgreSQL container may already exist"
        wait_for_service 5432 "PostgreSQL"
    fi
fi

# ============================================
# START SERVICES
# ============================================

# Backend
echo "Starting Backend service..."
cd backend
python main.py &
BACKEND_PID=$!
wait_for_service 3004 "Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:3004"
echo "  API Docs: http://localhost:3004/docs"
echo ""
echo "Decision Capture & Tracking Features:"
echo "  - Decision API: http://localhost:3004/api/decisions"
echo "  - GitHub Webhooks: http://localhost:3004/webhooks/github"
echo ""
echo "Backend Process ID: $BACKEND_PID"
echo ""
echo -e "${GREEN}To stop services: kill $BACKEND_PID${NC}"
echo ""

# Health check
echo "Performing health check..."
curl -s http://localhost:3004/health | jq '.' 2>/dev/null || curl -s http://localhost:3004/health

echo ""
echo -e "${GREEN}Development environment is ready!${NC}"