"""
Multi-channel notification service
"""
import asyncio
import logging
from abc import ABC, abstractmethod
from datetime import datetime, time
from typing import List, Dict, Optional, Any
from enum import Enum
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from ..models.alerts import (
    Alert,
    Notification,
    NotificationType,
    NotificationStatus,
    NotificationPreferences
)
from .alert_engine import AlertEngine

logger = logging.getLogger(__name__)


class NotificationChannel(ABC):
    """Abstract base class for notification channels"""

    @abstractmethod
    async def send(self, notification: Notification) -> bool:
        """
        Send a notification through this channel

        Args:
            notification: Notification to send

        Returns:
            True if successful, False otherwise
        """
        pass

    @abstractmethod
    def validate_recipient(self, recipient: str) -> bool:
        """
        Validate recipient address

        Args:
            recipient: Recipient address

        Returns:
            True if valid, False otherwise
        """
        pass


class EmailNotificationChannel(NotificationChannel):
    """Email notification channel"""

    def __init__(self, smtp_host: str, smtp_port: int, username: str, password: str):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password

    async def send(self, notification: Notification) -> bool:
        """Send email notification"""
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.username
            msg['To'] = notification.recipient
            msg['Subject'] = notification.title

            # Add body
            body = self._format_email_body(notification)
            msg.attach(MIMEText(body, 'html'))

            # Send email
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)

            logger.info(f"Email sent to {notification.recipient}")
            return True

        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    def validate_recipient(self, recipient: str) -> bool:
        """Validate email address"""
        import re
        pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        return bool(re.match(pattern, recipient))

    def _format_email_body(self, notification: Notification) -> str:
        """Format email body"""
        return f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                    <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
                        <h1 style="color: #dc3545; margin: 0;">{notification.title}</h1>
                    </div>

                    <div style="background-color: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
                        <p style="font-size: 16px;">{notification.content}</p>

                        {self._format_alert_details(notification.metadata)}
                    </div>

                    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; font-size: 12px; color: #6c757d;">
                        <p>This alert was generated by CBSC Trading System at {notification.created_at.strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
                    </div>
                </div>
            </body>
        </html>
        """

    def _format_alert_details(self, metadata: Dict[str, Any]) -> str:
        """Format alert details for email"""
        if not metadata or 'conditions' not in metadata:
            return ""

        details = "<h3 style='margin-top: 20px; color: #495057;'>Alert Details:</h3><ul style='margin: 10px 0; padding-left: 20px;'>"

        for condition_data in metadata['conditions']:
            condition = condition_data['condition']
            value = condition_data['value']
            triggered = condition_data['triggered']

            details += f"""
                <li style="margin: 5px 0;">
                    <strong>{condition.metric.replace('_', ' ').title()}</strong>:
                    {value:.4f} (Threshold: {condition.operator} {condition.threshold})
                    <span style="color: {'#28a745' if triggered else '#dc3545'};">
                        {'✓' if triggered else '✗'}
                    </span>
                </li>
            """

        details += "</ul>"
        return details


class BrowserPushNotificationChannel(NotificationChannel):
    """Browser push notification channel"""

    def __init__(self, vapid_keys: Dict[str, str]):
        self.vapid_keys = vapid_keys
        self.subscriptions: Dict[int, List[Dict]] = {}

    async def send(self, notification: Notification) -> bool:
        """Send browser push notification"""
        try:
            # Get user's subscriptions
            user_id = notification.metadata.get('user_id')
            if not user_id or user_id not in self.subscriptions:
                logger.warning(f"No push subscriptions found for user {user_id}")
                return False

            subscriptions = self.subscriptions[user_id]
            success_count = 0

            for sub in subscriptions:
                if await self._send_to_subscription(notification, sub):
                    success_count += 1

            logger.info(f"Push notification sent to {success_count}/{len(subscriptions)} subscriptions")
            return success_count > 0

        except Exception as e:
            logger.error(f"Failed to send push notification: {e}")
            return False

    async def _send_to_subscription(self, notification: Notification, subscription: Dict) -> bool:
        """Send notification to a specific subscription"""
        # In production, use pywebpush or similar library
        # For demo, simulate success
        import random
        return random.random() > 0.1  # 90% success rate

    def validate_recipient(self, recipient: str) -> bool:
        """Validate push subscription endpoint"""
        return recipient.startswith('https://') or recipient.startswith('http://')

    def add_subscription(self, user_id: int, subscription: Dict):
        """Add a new push subscription"""
        if user_id not in self.subscriptions:
            self.subscriptions[user_id] = []
        self.subscriptions[user_id].append(subscription)

    def remove_subscription(self, user_id: int, subscription: Dict):
        """Remove a push subscription"""
        if user_id in self.subscriptions:
            try:
                self.subscriptions[user_id].remove(subscription)
            except ValueError:
                pass


class InAppNotificationChannel(NotificationChannel):
    """In-app notification channel"""

    def __init__(self):
        self.notifications: Dict[int, List[Dict]] = {}

    async def send(self, notification: Notification) -> bool:
        """Store in-app notification"""
        try:
            user_id = notification.metadata.get('user_id', 0)

            if user_id not in self.notifications:
                self.notifications[user_id] = []

            notif_data = {
                'id': str(notification.id),
                'title': notification.title,
                'content': notification.content,
                'severity': notification.metadata.get('severity', 'low'),
                'timestamp': notification.created_at.isoformat(),
                'read': False
            }

            self.notifications[user_id].append(notif_data)

            # Keep only last 50 notifications per user
            if len(self.notifications[user_id]) > 50:
                self.notifications[user_id] = self.notifications[user_id][-50:]

            logger.info(f"In-app notification stored for user {user_id}")
            return True

        except Exception as e:
            logger.error(f"Failed to store in-app notification: {e}")
            return False

    def validate_recipient(self, recipient: str) -> bool:
        """In-app notifications don't need recipient validation"""
        return True

    def get_user_notifications(self, user_id: int, unread_only: bool = False) -> List[Dict]:
        """Get notifications for a user"""
        if user_id not in self.notifications:
            return []

        notifications = self.notifications[user_id]

        if unread_only:
            notifications = [n for n in notifications if not n['read']]

        # Sort by timestamp descending
        return sorted(notifications, key=lambda x: x['timestamp'], reverse=True)

    def mark_as_read(self, user_id: int, notification_id: str):
        """Mark notification as read"""
        if user_id in self.notifications:
            for notif in self.notifications[user_id]:
                if notif['id'] == notification_id:
                    notif['read'] = True
                    break

    def mark_all_as_read(self, user_id: int):
        """Mark all notifications as read"""
        if user_id in self.notifications:
            for notif in self.notifications[user_id]:
                notif['read'] = True


class SMSNotificationChannel(NotificationChannel):
    """SMS notification channel"""

    def __init__(self, api_key: str, api_secret: str, from_number: str):
        self.api_key = api_key
        self.api_secret = api_secret
        self.from_number = from_number

    async def send(self, notification: Notification) -> bool:
        """Send SMS notification"""
        try:
            # In production, use Twilio or similar service
            # For demo, simulate success
            import random
            success = random.random() > 0.05  # 95% success rate

            if success:
                logger.info(f"SMS sent to {notification.recipient}")
            else:
                logger.error(f"Failed to send SMS to {notification.recipient}")

            return success

        except Exception as e:
            logger.error(f"Failed to send SMS: {e}")
            return False

    def validate_recipient(self, recipient: str) -> bool:
        """Validate phone number"""
        import re
        # Simple validation for international phone numbers
        pattern = r'^\+?[1-9]\d{1,14}$'
        return bool(re.match(pattern, recipient))


class WebhookNotificationChannel(NotificationChannel):
    """Webhook notification channel"""

    async def send(self, notification: Notification) -> bool:
        """Send webhook notification"""
        try:
            import aiohttp

            url = notification.recipient
            payload = {
                'id': str(notification.id),
                'title': notification.title,
                'content': notification.content,
                'severity': notification.metadata.get('severity'),
                'timestamp': notification.created_at.isoformat(),
                'metadata': notification.metadata
            }

            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=10) as response:
                    if response.status == 200:
                        logger.info(f"Webhook sent to {url}")
                        return True
                    else:
                        logger.error(f"Webhook failed with status {response.status}")
                        return False

        except Exception as e:
            logger.error(f"Failed to send webhook: {e}")
            return False

    def validate_recipient(self, recipient: str) -> bool:
        """Validate webhook URL"""
        import re
        pattern = r'^https?://.+'
        return bool(re.match(pattern, recipient))


class NotificationService:
    """Main notification service"""

    def __init__(self):
        self.channels: Dict[NotificationType, NotificationChannel] = {}
        self.quiet_hours_cache: Dict[int, NotificationPreferences] = {}

    def register_channel(self, channel_type: NotificationType, channel: NotificationChannel):
        """Register a notification channel"""
        self.channels[channel_type] = channel

    async def send_notifications(
        self,
        alert: Alert,
        preferences: NotificationPreferences,
        channels: List[NotificationType]
    ) -> List[Notification]:
        """
        Send notifications through multiple channels

        Args:
            alert: Alert to send notifications for
            preferences: User notification preferences
            channels: List of channels to use

        Returns:
            List of created notifications
        """
        notifications = []

        for channel_type in channels:
            # Check if channel is enabled in preferences
            if not preferences.channels.get(channel_type, False):
                continue

            # Check quiet hours
            if self._is_quiet_hours(preferences) and channel_type != NotificationType.IN_APP:
                logger.info(f"Skipping {channel_type} notification during quiet hours")
                continue

            # Get channel
            channel = self.channels.get(channel_type)
            if not channel:
                logger.warning(f"Notification channel {channel_type} not registered")
                continue

            # Get recipient
            recipient = self._get_recipient(alert, channel_type, preferences)
            if not recipient:
                logger.warning(f"No recipient for {channel_type} notification")
                continue

            # Create notification
            notification = Notification(
                alert_id=alert.id,
                user_id=alert.user_id,
                type=channel_type,
                title=alert.title,
                content=alert.message,
                recipient=recipient,
                metadata={
                    'alert_id': str(alert.id),
                    'user_id': alert.user_id,
                    'severity': alert.severity.value,
                    'strategy_id': alert.strategy_id
                }
            )

            # Send notification
            try:
                success = await channel.send(notification)

                if success:
                    notification.status = NotificationStatus.SENT
                    notification.sent_at = datetime.utcnow()
                else:
                    notification.status = NotificationStatus.FAILED

            except Exception as e:
                logger.error(f"Error sending {channel_type} notification: {e}")
                notification.status = NotificationStatus.FAILED
                notification.error_message = str(e)

            notifications.append(notification)

        return notifications

    def _is_quiet_hours(self, preferences: NotificationPreferences) -> bool:
        """Check if current time is within quiet hours"""
        if not preferences.quiet_hours_enabled:
            return False

        now = datetime.now().time()
        start_time = preferences.quiet_hours_start
        end_time = preferences.quiet_hours_end

        # Handle crossing midnight
        if start_time > end_time:
            return now >= start_time or now <= end_time
        else:
            return start_time <= now <= end_time

    def _get_recipient(
        self,
        alert: Alert,
        channel_type: NotificationType,
        preferences: NotificationPreferences
    ) -> Optional[str]:
        """Get recipient for notification channel"""
        # In production, get from user profile
        # For demo, return mock recipients
        recipients = {
            NotificationType.EMAIL: f"user{alert.user_id}@example.com",
            NotificationType.SMS: f"+1234567890",
            NotificationType.WEBHOOK: "https://example.com/webhook/alert",
            NotificationType.BROWSER_PUSH: "https://fcm.googleapis.com/fcm/send",
            NotificationType.IN_APP: str(alert.user_id)
        }

        return recipients.get(channel_type)


# Initialize notification service
notification_service = NotificationService()

# Configure channels (in production, load from config)
def configure_notification_services(config: Dict[str, Any]):
    """Configure notification channels"""
    # Email channel
    if 'email' in config:
        notification_service.register_channel(
            NotificationType.EMAIL,
            EmailNotificationChannel(
                smtp_host=config['email']['smtp_host'],
                smtp_port=config['email']['smtp_port'],
                username=config['email']['username'],
                password=config['email']['password']
            )
        )

    # Browser push channel
    if 'push' in config:
        notification_service.register_channel(
            NotificationType.BROWSER_PUSH,
            BrowserPushNotificationChannel(
                vapid_keys=config['push']['vapid_keys']
            )
        )

    # SMS channel
    if 'sms' in config:
        notification_service.register_channel(
            NotificationType.SMS,
            SMSNotificationChannel(
                api_key=config['sms']['api_key'],
                api_secret=config['sms']['api_secret'],
                from_number=config['sms']['from_number']
            )
        )

    # In-app channel
    notification_service.register_channel(
        NotificationType.IN_APP,
        InAppNotificationChannel()
    )

    # Webhook channel
    if 'webhook' in config:
        # Webhooks are configured per user
        pass