---
apiVersion: v1
kind: Namespace
metadata:
  name: cbsc-system
  labels:
    name: cbsc-system
    environment: production
    project: cbsc-strategy-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: cbsc-monitoring
  labels:
    name: cbsc-monitoring
    environment: production
    project: cbsc-strategy-management