---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cbsc-system
  labels:
    app: postgres
    component: database
data:
  postgresql.conf: |
    # PostgreSQL Configuration File
    # -----------------------------

    # CONNECTIONS AND AUTHENTICATION
    # -----------------------------

    # Connection settings
    listen_addresses = '*'
    port = 5432
    max_connections = 200
    superuser_reserved_connections = 3

    # Security and Authentication
    authentication_timeout = 1min
    password_encryption = scram-sha-256
    db_user_namespace = false

    # RESOURCE USAGE (except WAL)
    # -------------------------

    # Memory
    shared_buffers = 256MB
    huge_pages = try
    temp_buffers = 32MB
    max_prepared_transactions = 0
    work_mem = 4MB
    hash_mem_multiplier = 1.0
    maintenance_work_mem = 64MB
    autovacuum_work_mem = -1
    max_stack_depth = 2MB
    shared_memory_type = mmap
    dynamic_shared_memory_type = posix

    # Kernel Resource Usage
    max_files_per_process = 1000

    # WRITE-AHEAD LOG
    # --------------

    # Settings
    wal_level = replica
    fsync = on
    synchronous_commit = on
    wal_sync_method = fsync
    full_page_writes = on
    wal_compression = off
    wal_init_zero = on
    wal_recycle = on
    wal_buffers = -1
    wal_writer_delay = 200ms
    wal_writer_flush_after = 1MB

    # Checkpoints
    checkpoint_timeout = 5min
    checkpoint_completion_target = 0.9
    checkpoint_flush_after = 256kB
    checkpoint_warning = 30s
    max_wal_size = 1GB
    min_wal_size = 80MB

    # Archiving
    archive_mode = off
    archive_command = ''
    archive_timeout = 0

    # REPLICATION
    # ----------

    # Sending Servers
    max_wal_senders = 10
    max_replication_slots = 10
    wal_keep_size = 0
    wal_sender_timeout = 60s
    track_commit_timestamp = off

    # Standby Servers
    hot_standby = on
    max_standby_archive_delay = 30s
    max_standby_streaming_delay = 30s
    wal_receiver_create_temp_slot = off
    hot_standby_feedback = off
    wal_receiver_status_interval = 10s
    hot_standby_feedback_interval = 1s
    wal_receiver_timeout = 60s
    wal_retrieve_retry_interval = 5s
    recovery_min_apply_delay = 0

    # SUBSCRIPTIONS
    # -------------

    # Logical Replication Worker Settings
    max_logical_replication_workers = 4
    max_sync_workers_per_subscription = 2

    # QUERY TUNING
    # ------------

    # Planner Method Configuration
    enable_bitmapscan = on
    enable_hashagg = on
    enable_hashjoin = on
    enable_indexscan = on
    enable_indexonlyscan = on
    enable_material = on
    enable_mergejoin = on
    enable_nestloop = on
    enable_parallel_append = on
    enable_parallel_hash = on
    enable_partition_pruning = on
    enable_partitionwise_join = off
    enable_partitionwise_aggregate = off
    enable_seqscan = on
    enable_sort = on
    enable_tidscan = on

    # Planner Cost Constants
    seq_page_cost = 1.0
    random_page_cost = 4.0
    cpu_tuple_cost = 0.01
    cpu_index_tuple_cost = 0.005
    cpu_operator_cost = 0.0025
    parallel_tuple_cost = 0.1
    parallel_setup_cost = 1000.0
    jit_above_cost = 100000
    jit_inline_above_cost = 500000
    jit_optimize_above_cost = 500000

    # Genetic Query Optimizer
    geqo = on
    geqo_threshold = 12
    geqo_effort = 5
    geqo_pool_size = 0
    geqo_generations = 0
    geqo_selection_bias = 2.0
    geqo_seed = 0.0

    # Other Planner Options
    default_statistics_target = 100
    constraint_exclusion = partition
    cursor_tuple_fraction = 0.1
    from_collapse_limit = 8
    join_collapse_limit = 8
    force_parallel_mode = off
    jit = on

    # REPORTING AND LOGGING
    # --------------------

    # Where to Log
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_file_mode = 0600
    log_truncate_on_rotation = off
    log_rotation_age = 1d
    log_rotation_size = 10MB
    syslog_facility = 'LOCAL0'
    syslog_ident = 'postgres'
    syslog_sequence_numbers = on
    syslog_split_messages = on
    event_source = 'PostgreSQL'

    # When to Log
    log_min_messages = warning
    log_min_error_statement = error
    log_min_duration_statement = 1000

    # What to Log
    debug_print_parse = off
    debug_print_rewritten = off
    debug_print_plan = off
    debug_pretty_print = on
    log_checkpoints = on
    log_connections = off
    log_disconnections = off
    log_duration = off
    log_error_verbosity = default
    log_hostname = off
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    log_lock_waits = off
    log_parameter_max_length = -1
    log_parameter_max_length_on_error = 0
    log_statement = 'none'
    log_replication_commands = off
    log_temp_files = 10MB
    log_timezone = 'UTC'

    # PROCESS TITLE
    -------------

    cluster_name = 'cbsc-postgres'
    update_process_title = on

    # STATISTICS
    # ----------

    # Query/Index Statistics Collector
    track_activities = on
    track_counts = on
    track_io_timing = off
    track_functions = none
    track_activity_query_size = 1024
    stats_temp_directory = 'pg_stat_tmp'

    # Statistics Monitoring
    compute_query_id = auto
    log_statement_stats = off
    log_parser_stats = off
    log_planner_stats = off
    log_executor_stats = off

    # AUTOVACUUM
    # ----------

    # Autovacuum settings
    autovacuum = on
    log_autovacuum_min_duration = 0
    autovacuum_max_workers = 3
    autovacuum_naptime = 1min
    autovacuum_vacuum_threshold = 50
    autovacuum_analyze_threshold = 50
    autovacuum_vacuum_scale_factor = 0.2
    autovacuum_analyze_scale_factor = 0.1
    autovacuum_freeze_max_age = 200000000
    autovacuum_multixact_freeze_max_age = 400000000
    autovacuum_vacuum_cost_delay = 2ms
    autovacuum_vacuum_cost_limit = -1

    # CLIENT CONNECTION DEFAULTS
    # ---------------------------

    # Statement Behavior
    client_min_messages = notice
    search_path = '"$user", public'
    row_security = on
    default_table_access_method = 'heap'
    default_tablespace = ''
    temp_tablespaces = ''
    default_toast_compression = 'pglz'
    check_function_bodies = on
    default_transaction_isolation = 'read committed'
    default_transaction_read_only = off
    default_transaction_deferrable = off
    session_replication_role = 'origin'
    statement_timeout = 0
    lock_timeout = 0
    idle_in_transaction_session_timeout = 0
    vacuum_freeze_min_age = 50000000
    vacuum_freeze_table_age = 150000000
    vacuum_multixact_freeze_min_age = 5000000
    vacuum_multixact_freeze_table_age = 150000000
    vacuum_cleanup_index_scale_factor = 0.1
    pg_stat_statements.track = none
    pg_stat_statements.max = 1000
    pg_stat_statements.track_utility = on
    pg_stat_statements.save = on

    # Locale and Formatting
    datestyle = 'iso, mdy'
    intervalstyle = 'postgres'
    timezone = 'UTC'
    timezone_abbreviations = 'Default'
    extra_float_digits = 1
    client_encoding = sql_ascii

    # Shared Library Preloading
    local_preload_libraries = ''
    session_preload_libraries = ''
    jit_provider = 'llvmjit'

    # Other Defaults
    dynamic_library_path = '$libdir'
    gin_fuzzy_search_limit = 0

    # VERSION AND PLATFORM COMPATIBILITY
    # ----------------------------------

    # Previous PostgreSQL Versions
    array_nulls = on
    backslash_quote = safe_encoding
    default_with_oids = off
    escape_string_warning = on
    lo_compat_privileges = off
    operator_precedence_warning = off
    quote_all_identifiers = off
    standard_conforming_strings = on
    synchronize_seqscans = on

    # Other Platforms and Clients
    transform_null_equals = off

    # CUSTOMIZED OPTIONS
    # ------------------

    # Add settings for extensions here
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File
    # TYPE  DATABASE        USER            ADDRESS                 METHOD

    # "local" is for Unix domain socket connections only
    local   all             all                                     trust

    # IPv4 local connections:
    host    all             all             127.0.0.1/32            md5
    host    all             all             0.0.0.0/0               md5

    # IPv6 local connections:
    host    all             all             ::1/128                 md5

    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            md5
    host    replication     all             ::1/128                 md5