"""
Strategy Implementation for Backtesting
回測策略實現

Provides base strategy class and common strategy implementations
for backtesting purposes.
為回測提供基礎策略類和常用策略實現。
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd
import numpy as np


class StrategyType(Enum):
    """Strategy type enumeration."""
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    TREND_FOLLOWING = "trend_following"
    VOLATILITY = "volatility"
    CUSTOM = "custom"


@dataclass
class StrategySignal:
    """Trading signal generated by strategy."""
    symbol: str
    signal_type: str  # BUY, SELL, HOLD
    confidence: float = 1.0  # 0.0 to 1.0
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


class Strategy(ABC):
    """Base strategy class."""

    def __init__(
        self,
        name: str,
        strategy_type: StrategyType,
        parameters: Optional[Dict[str, Any]] = None
    ):
        self.name = name
        self.strategy_type = strategy_type
        self.parameters = parameters or {}
        self.signals_generated = 0

    @abstractmethod
    async def generate_signals(
        self,
        market_data: Dict[str, pd.DataFrame],
        timestamp: datetime
    ) -> List[StrategySignal]:
        """Generate trading signals for given timestamp."""
        pass

    def get_parameters(self) -> Dict[str, Any]:
        """Get strategy parameters."""
        return self.parameters.copy()


class SMACrossoverStrategy(Strategy):
    """Simple Moving Average Crossover Strategy."""

    def __init__(self, fast_period: int = 20, slow_period: int = 50):
        super().__init__(
            name="SMA_Crossover",
            strategy_type=StrategyType.TREND_FOLLOWING,
            parameters={
                "fast_period": fast_period,
                "slow_period": slow_period
            }
        )
        self.fast_period = fast_period
        self.slow_period = slow_period
        self.position_state = {}  # Track position state for each symbol

    async def generate_signals(
        self,
        market_data: Dict[str, pd.DataFrame],
        timestamp: datetime
    ) -> List[StrategySignal]:
        """Generate SMA crossover signals."""
        signals = []

        for symbol, df in market_data.items():
            if len(df) < self.slow_period:
                continue

            # Calculate SMAs
            df["sma_fast"] = df["close"].rolling(window=self.fast_period).mean()
            df["sma_slow"] = df["close"].rolling(window=self.slow_period).mean()

            # Get current and previous values
            current_row = df.iloc[-1]
            prev_row = df.iloc[-2] if len(df) > 1 else current_row

            current_fast = current_row["sma_fast"]
            current_slow = current_row["sma_slow"]
            prev_fast = prev_row["sma_fast"]
            prev_slow = prev_row["sma_slow"]

            # Initialize position state if not exists
            if symbol not in self.position_state:
                self.position_state[symbol] = "FLAT"

            # Generate crossover signals
            if (prev_fast <= prev_slow and current_fast > current_slow and
                self.position_state[symbol] == "FLAT"):
                # Golden cross - buy signal
                signals.append(StrategySignal(
                    symbol=symbol,
                    signal_type="BUY",
                    confidence=0.7,
                    timestamp=timestamp,
                    metadata={
                        "fast_sma": current_fast,
                        "slow_sma": current_slow,
                        "crossover_type": "golden_cross"
                    }
                ))
                self.position_state[symbol] = "LONG"

            elif (prev_fast >= prev_slow and current_fast < current_slow and
                  self.position_state[symbol] == "LONG"):
                # Death cross - sell signal
                signals.append(StrategySignal(
                    symbol=symbol,
                    signal_type="SELL",
                    confidence=0.7,
                    timestamp=timestamp,
                    metadata={
                        "fast_sma": current_fast,
                        "slow_sma": current_slow,
                        "crossover_type": "death_cross"
                    }
                ))
                self.position_state[symbol] = "FLAT"

        self.signals_generated += len(signals)
        return signals


class RSIStrategy(Strategy):
    """Relative Strength Index Strategy."""

    def __init__(self, period: int = 14, oversold: float = 30, overbought: float = 70):
        super().__init__(
            name="RSI_Mean_Reversion",
            strategy_type=StrategyType.MEAN_REVERSION,
            parameters={
                "period": period,
                "oversold": oversold,
                "overbought": overbought
            }
        )
        self.period = period
        self.oversold = oversold
        self.overbought = overbought
        self.position_state = {}

    async def generate_signals(
        self,
        market_data: Dict[str, pd.DataFrame],
        timestamp: datetime
    ) -> List[StrategySignal]:
        """Generate RSI-based signals."""
        signals = []

        for symbol, df in market_data.items():
            if len(df) < self.period + 1:
                continue

            # Calculate RSI
            delta = df["close"].diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=self.period).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=self.period).mean()
            rs = gain / loss.replace(0, np.nan)
            df["rsi"] = 100 - (100 / (1 + rs))

            current_rsi = df["rsi"].iloc[-1]

            # Initialize position state if not exists
            if symbol not in self.position_state:
                self.position_state[symbol] = "FLAT"

            # Generate signals based on RSI levels
            if current_rsi < self.oversold and self.position_state[symbol] == "FLAT":
                # Oversold - buy signal
                confidence = min(1.0, (self.oversold - current_rsi) / 20)
                signals.append(StrategySignal(
                    symbol=symbol,
                    signal_type="BUY",
                    confidence=confidence,
                    timestamp=timestamp,
                    metadata={
                        "rsi": current_rsi,
                        "signal_type": "oversold"
                    }
                ))
                self.position_state[symbol] = "LONG"

            elif current_rsi > self.overbought and self.position_state[symbol] == "LONG":
                # Overbought - sell signal
                confidence = min(1.0, (current_rsi - self.overbought) / 20)
                signals.append(StrategySignal(
                    symbol=symbol,
                    signal_type="SELL",
                    confidence=confidence,
                    timestamp=timestamp,
                    metadata={
                        "rsi": current_rsi,
                        "signal_type": "overbought"
                    }
                ))
                self.position_state[symbol] = "FLAT"

        self.signals_generated += len(signals)
        return signals


class StrategyResult:
    """Strategy backtest result."""

    def __init__(
        self,
        strategy_name: str,
        total_return: float,
        sharpe_ratio: float,
        max_drawdown: float,
        win_rate: float,
        total_trades: int
    ):
        self.strategy_name = strategy_name
        self.total_return = total_return
        self.sharpe_ratio = sharpe_ratio
        self.max_drawdown = max_drawdown
        self.win_rate = win_rate
        self.total_trades = total_trades

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "strategy_name": self.strategy_name,
            "total_return": self.total_return,
            "sharpe_ratio": self.sharpe_ratio,
            "max_drawdown": self.max_drawdown,
            "win_rate": self.win_rate,
            "total_trades": self.total_trades
        }