---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cbsc-system
  labels:
    app: cbsc-frontend
    component: web
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: cbsc-frontend
    component: web
    tier: frontend
  sessionAffinity: None